services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cian_scraper
    restart: no
    env_file:
      - .env
    volumes:
      - ./:/db
    networks:
      - external
    environment:
      - PYTHONPATH=/app
  
networks:
  external:
    driver: bridge
