version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    container_name: cian_db
    ports:
      - "${POSTGRES_PORT}:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  bot:
    image: neimes/cian_scraper:latest
    restart: always
    container_name: cian_scraper
    depends_on:
      - db
    env_file:
      - .env
    
volumes:
  postgres_data:  
  