services:
  bot:
    image: neimes/cian_scraper:latest
    container_name: cian_scraper
    restart: unless-stopped
    volumes:
      - ./:/db
    environment:
      - PYTHONPATH=${PYTHONPATH}
      - DATABASE_URL=${DATABASE_URL}
      - LOGGER_MODE=${LOGGER_MODE}
      - TELEGRAM_API_KEY=${TELEGRAM_API_KEY}
      - TELEGRAM_ADMIN_ID=${TELEGRAM_ADMIN_ID}
