services:
  db:
    image: postgres:14
    container_name: database
    restart: always
    env_file:
      - .env
    networks:
      internal:
      external:
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"

  bot:
    image: neimes/cian_scraper:latest
    container_name: cian_scraper
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - internal

volumes:
  postgres_data:

networks:
  internal:
    driver: bridge
    internal: true
  external:
    driver: bridge
